sudo: false
language: erlang
otp_release:
   - 19.3
   - 20.3
   - 21.3
   - 22.3
   - 23.1
script: >
  curl https://s3.amazonaws.com/rebar3/rebar3 -o rebar3
  && ./rebar3 do xref, eunit, ct, dialyze
